### ISSUE TITLE
Fetching a list of recipients sometimes takes as longer than necessary

### ISSUE THREAD

**Issue by oreHGA** [vunderkind/good-faith#15]
Device: iPhone, PC
Browser: Safari, Edge

Not sure exactly what changed, but fetching a list of people to donate to intermittently takes approx. 8s before showing me the list. After multiple trials it seems to respond a lost faster though

## Potential Fixes
- Moving randomization logic for displaying recipients to the backend and the frontend as just display could help fix this
- Like @olucode mentioned, the Heroku dyno warm up time could also be an additional factor we need to consider

**Comment by vunderkind** [comment]
Additional, potentially useful context:

<img width="307" alt="Screenshot 2020-04-03 at 02 40 02" src="https://user-images.githubusercontent.com/13500685/78315283-75116b80-7554-11ea-83d0-9d79cb09b2ba.png">

**Comment by oreHGA** [comment]
Infra changes have eliminated the need for the Heroku sleep/warm up time that also contributed to this
